version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  test:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew testDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  buildDebug:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
  buildRelease:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew bundleRelease
      - store_artifacts:
          path: app/build/outputs/bundle
          destination: bundle

workflows:
  version: 2.1
  test-and-buildDebug:
    jobs:
      - test
      - buildDebug
  test-and-buildRelease:
    jobs:
      - test
      - buildRelease:
          requires:
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/