version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  test:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew testDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  build:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew assembleRelease bundleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apk
      - store_artifacts:
          path: app/build/outputs/bundle
          destination: bundle

workflows:
  version: 2.1
  test-and-build:
    jobs:
      - test
      - build:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test