version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  test:
    executor: android/android
    steps:
      - checkout
      - run:
          command: ./gradlew testDebugUnitTest
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    executor: android/android
    steps:
      - run:
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk
          destinaion: apk

workflows:
  version: 2.1
  lint-and-test:
    jobs:
      - test:
      - build:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test