version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    steps:
      - checkout
      - run:
          name: Lint
          command: ./gradlew lintDebug
      - run:
          name: Test
          command: ./gradlew testDebugUnitTest
      - run:
          name: Build
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs
          destinaion: outputs
      - store_test_results:
          path: app/build/test-results